def():
    print("hello")
    print("learning")
    print("git")
    print("is")
    print("fun")
    print("!")
    print(" ")
    print(" ")
    print("@")
    print("!")
    print"G@@GL3")
    print("A")
    print("B")
    print("C")
    print("D")
